rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  queue: "events_queue"

email:
  smtp_host: "smtp.example.com"
  smtp_port: 587
  sender_email: "nikitakazunin@yandex.ru"
  sender_password: "Xizntccpx7mzlzvf@jcm"
  recipient_email: "recipient@example.com"
  subject: "Event Notification"