rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  queue: "events_queue"

email:
  smtp_host: "smtp.yandex.ru"
  smtp_port: 587
  sender_email: "nikitakazunin@yandex.ru"
  sender_password: "yeokeswsgtwodplu"
  recipient_email: "nikitakazuninnn@yandex.ru"
  subject: "Event Notification"